#!/bin/bash

if [ -n "$1" ];then
	
	case $1 in
		vm0)
			MAC='DE:AD:BE:EF:12:03';;
		vm1)
			MAC='DE:AD:BE:EF:12:04';;
		vm2)
			MAC='DE:AD:BE:EF:12:05';;
		vm3)
			MAC='DE:AD:BE:EF:12:06';;
		vm4)
			MAC='DE:AD:BE:EF:12:07';;
		*)
			echo "Usage: $0 vm{0|1|2|3|4}"
			exit 1
	esac

	echo "starting $1"

	modprobe vhost_net
	qemu-system-x86_64 --nographic \
		-machine accel=kvm \
		-no-reboot \
		-kernel ./platform-i586/images/linuximage \
		-hda ./platform-i586/images/hd.img \
		-m 256 \
		-append "root=/dev/sda1 rw console=ttyS0,115200 debug" \
		-incoming "exec: gzip -c -d $1.gz" \
		-device virtio-net-pci,netdev=net0,mac=$MAC -netdev tap,vhost=on,id=net0,script=qemu-ifup.sh
else
	echo "error: need name for vm snapshot"
fi
